apiVersion: v1
kind: Pod
metadata:
  name: casestudy-pipeline
spec:
  containers:
  - name: population-container
    image: stefannikesh/casestudy-engineering:population
  - name: birth-container
    image: stefannikesh/casestudy-engineering:birth
  - name: migration-container
    image: stefannikesh/casestudy-engineering:migration
  - name: transform-container
    image: stefannikesh/casestudy-engineering:transform
  restartPolicy: Never